version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR... | tee -a log.txt
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pulling Docker Images for cache ... | tee -a log.txt
      - docker-compose pull --ignore-pull-failures --parallel 2>&1 | tee -a log.txt
  build:
    commands:
      - echo Build started on `date` | tee -a log.txt
      - echo Building the Docker image ... | tee -a log.txt
      - docker-compose build 2>&1 | tee -a log.txt   
  post_build:
    commands:
      - echo Build completed on `date` | tee -a log.txt
      - echo Pushing the Docker image... | tee -a log.txt
      - docker-compose push 2>&1 | tee -a log.txt