# Generated by Django 4.1 on 2022-11-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_scorelog_test_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorelog',
            name='test_col',
        ),
    ]
