# Generated by Django 4.1 on 2022-11-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_scorelog_test_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorelog',
            name='score_2',
            field=models.CharField(default='EMPTY_BRO', max_length=10),
        ),
    ]
